### ISSUE TITLE
Bug with ep.plot_rgb(stretch=True)

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earthpy#282]
**Describe the bug**
When plotting landsat RGB bands with `plot_rgb()`, I tried to apply a stretch, since the image was "washed out". When I did `ep.plot_rgb(array, stretch=True)`, I get a warning saying "RuntimeWarning: overflow encountered in short_scalars: crange = cmax - cmin". 

Addionally, `es.bytescale()`, which is used in `ep.plot_rgb()`, gives the following error that stops the plot: "ValueError: `cmax` should be larger than `cmin`." 

When looking into this, I did `array.max()` and `array.min()`, which are the default cmax/cmin values. The maximum was 13016, and the minimum was -9999, which is a N/A value. There were other negative values in the array besides -9999, I'm not sure what they represented. 

To get around this bug, before running the `ep.plot_rgb()` function, I ran `output = es.bytescale(array, cmin = 0)`. After this is run, if you run `ep.plot_rgb(output, stretch=True)` the expected behavior happens, with no errors. If cmin is set not to negative, but to the next lowest value in the input array, such as -1737 in this case, the array does not stretch well, but there are no errors. 

**To Reproduce**
This code block should reproduce the behavior:

```
import os
from glob import glob
import earthpy as et
import earthpy.spatial as es
import earthpy.plot as ep

data = et.data.get_data("cs-test-landsat")
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))

landsat_bands = "data/cs-test-landsat/LC08_L1TP_034032_20160621_20170221_01_T1_sr_band*[2-4]*.tif"
stack_bands = glob(landsat_bands)
stack_bands.sort()
array, raster = es.stack(stack_bands)
ep.plot_rgb(array, stretch=True)
```
To make the error go away, add `array = es.bytescale(array, cmin=0)` above the `ep.plot_rgb()` line. 

**Expected behavior**
I expected the stretch to be able to run without doing any modification of the bytescale beforehand. 

**Screenshots**
The error message when no modification is made to the bytescale:
![image](https://user-images.githubusercontent.com/38253680/54788290-1cdf2400-4bf4-11e9-914c-392acb77c2a6.png)

The image when the cmin is set to the lowest value in the array that isn't an N/A value (-1737, in this case) before running the rgb plot.
![image](https://user-images.githubusercontent.com/38253680/54788523-e6ee6f80-4bf4-11e9-8d07-76e6e1a2b892.png)

The image when the cmin is set to 0 before running the rgb plot.
![image](https://user-images.githubusercontent.com/38253680/54788593-32a11900-4bf5-11e9-8def-ca0c3a794860.png)

**What Operating System Are you Running? **
 - Windows

If you have any questions let me know!

**Comment by lwasser** [comment]
this is a great issue @nkorinek  very specific. we will look into it - likely next week!!! thank you

**Comment by lwasser** [comment]
in this case, @nkorinek if you set na values to masked as follows, does it work for you?

```
import os
from glob import glob
import earthpy as et
import earthpy.spatial as es
import earthpy.plot as ep
import numpy as np
import matplotlib.pyplot as plt

data = et.data.get_data("cs-test-landsat")
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))

landsat_bands = "data/cs-test-landsat/LC08_L1TP_034032_20160621_20170221_01_T1_sr_band*[2-4]*.tif"
stack_bands = glob(landsat_bands)
stack_bands.sort()
arr, raster = es.stack(stack_bands)


arr_mask = np.ma.masked_where(arr == -9999, arr)
# Remove no data values

ep.plot_rgb(arr_mask, stretch=True)
plt.show()
```
it works for me. it seems as if the -9999 value is throwing things off. @joemcglinchy looping you in here.. we might need to think about

1. adding an option to mask na values in stack. this could be as simple as a call to `np.ma.where()`
2. Thinking about how we use bytescale for these types of applications. it doesn't make sense to scale to a na value. what is a good way to catch this however in the function?

**Comment by lwasser** [comment]
As a resolution to this

1. fix bytescale to coerce to dtype float for range calculation
2. add notes to the `plot_rgb` docs to ensure users remove the no data value before plotting -- could reference a vignette 
3. add nodata to stack -- see #293

**Comment by lwasser** [comment]
@nkorinek  we have made some updates to plot_rgb that should resolve this issue. Can you please test it o your computer?? and if it's resolved, we can close this issue!

**Comment by nkorinek** [comment]
@lwasser Hey, I've just updated earthpy and tested it again on my computer, but the same thing is still happening. I tried setting the na values like you recommended, and that didn't seem to do the trick either. It's still very washed out when I plot it without the prior bytescale modification.

**Comment by nkorinek** [comment]
Update: It works fine, the error was on my end :)

**Comment by nkorinek** [comment]
Closing issue since the error has been resolved @lwasser @joemcglinchy
